package org.jandj.mos.os

enum class ProcName {
    START_STOP, WAIT_FOR_JOB, MAIN_PROC, LOADER, JOB_GOVERNOR, VIRTUAL_MACHINE, INTERRUPT, PRINT_LINE, GET_LINE, JCL, IDLE
}
enum class ProcessState {
    RUN, READY, BLOCKED, READY_STOPPED, BLOCKED_STOPPED
}
enum class ResName {
    OS_STOP, VARTOTOJO_ATMINTIS, IVEDIMO_IRENGINYS, ISVEDIMO_IRENGINIS, VIRTUAL_MEMORY, UZDUOTIS_VM,
    ISVESTA_EILUTE, EILUTE_ATMINTYJE, // ProcessDescriptor
    PRANESIMAS_GETLINE, IVESTA_EILUTE,

    PRANESIMAS_PERTRAUKIMUI, PERTRAUKIMAS, // processor descr.
    RESUME_VM, // int intId

    PROG_PAVADINIMAS, IVEDIMO_SRAUTAS, PROG_SUPERVIZORINEJE, PRANESIMAS_LOADER,
    UZDUOTIS_IS_MAINPROC, // is MainProc
    UZDUOTIS_IS_JG, // is JG->VM
    KIETASIS_DISKAS,

}
enum class IntType{
    READY,

    PRS, PRN, P, IN, HALT, ST,

    ILLEGAL_ADDRESS, ILLEGAL_OPCODE, ILLEGAL_ASSIGNMENT
}



